version: '3'
services:
    dev:
        user: vscode
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - ..:/workspace:cached
            - bashhistory:/commandhistory
            - /var/run/docker.sock:/var/run/docker.sock
        command: sleep infinity

volumes:
    bashhistory:
            