version: '3'
services:
    dev:
        user: vscode
        build:
            context: .
            dockerfile: dev.Dockerfile
        environment:
            - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
        volumes:
            - ..:/workspace:cached
            - bashhistory:/commandhistory
            - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
            - /var/run/docker.sock:/var/run/docker-host.sock
        command: sleep infinity

volumes:
    bashhistory:
            